name: qimam
description: A new Flutter project.
publish_to: "none"
version: 0.0.6+6

environment:
  sdk: ">=3.0.0 <4.0.0"   # تم التحديث لدعم الإصدارات الجديدة من Firebase و MLKit

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localization: ^0.1.10
  introduction_screen: ^3.1.8
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.2.0
  flutter_screenutil: ^5.7.0
  auto_size_text: ^3.0.0
  animated_bottom_navigation_bar: ^1.2.0
  intl: ^0.20.2
  flutter_svg: ^2.0.5
  flutter_verification_code: ^1.1.6
  dotted_line: ^3.1.0
  tab_container: ^2.0.0
  flutter_switch: ^0.3.2
  toggle_switch: ^2.1.0
  im_stepper: ^1.0.1+1
  animate_do: ^3.0.2
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0

  # تم تحديث Firebase للإصدارات المتوافقة مع MLKit 2025
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3        # مهم جدًا: 15+ عشان GoogleDataTransport 10+
  flutter_local_notifications: ^17.2.2

  logger: ^2.0.2+1
  sprintf: ^7.0.0
  get: ^4.6.5
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  table_calendar: ^3.2.0
  dropdown_search: ^5.0.6
  pin_code_fields: ^8.0.1
  wakelock_plus: ^1.4.0
  file_picker: ^10.3.1
  change_app_package_name: ^1.1.0
  http: ^1.5.0
  rename: ^3.0.1
  delete_un_used_assets: ^1.0.1
  flutter_rating_bar: ^4.0.1
  month_picker_dialog: ^5.1.2
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  syncfusion_flutter_pdfviewer: ^31.1.21
  image_picker: ^1.0.7
  scribble: ^0.9.1
  face_camera: ^0.1.4
  custom_rating_bar: ^3.0.0
  share_plus: ^10.1.0
  percent_indicator: ^4.2.3
  pdf: ^3.11.1
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  confetti: ^0.8.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.13
  dart_code_metrics: ^4.19.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lang/en.json
    - lang/ar.json

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
    - family: Hacen Tunisia
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold-3.ttf
    - family: new-font
      fonts:
        - asset: assets/fonts/new_font.ttf
